spring:
  application:
    name: Curevo

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Kolkata
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}

#  cloudinary:
#    cloud_name: ${IMAGE_HOSTING_CLOUD_NAME}
#    api_key: ${IMAGE_HOSTING_API_KEY}
#    api_secret: ${IMAGE_HOSTING_API_SECRET}


  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
      file-size-threshold: 2MB


server:
  port: 8080
  tomcat:
    max-swallow-size: 50MB  # Allows large requests to be processed
