spring:
  application:
    name: Curevo

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Kolkata
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
      file-size-threshold: 2MB

  mail:
    host: in-v3.mailjet.com
    port: 587
    username: ${MAILJET_API_KEY}         # Mailjet public API key
    password: ${MAILJET_API_SECRET_KEY}      # Mailjet private API key
    protocol: smtp
    from: curevoapp@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 15000
          timeout: 15000
          writetimeout: 15000

server:
  port: 8080
  tomcat:
    max-swallow-size: 50MB
github:
  api:
    key: ${GITHUB_AI_API_KEY}