package com.certaint.curevo.enums;

public enum Specialization {
    CARDIOLOGY,
    NEUROLOGY,
    ONCOLOGY,
    ORTHOPEDICS,
    PEDIATRICS,
    DERMATOLOGY,
    GENERAL_PRACTITIONER,
    GYNECOLOGY,
    PSYCHIATRY,
    RADIOLOGY,
    SURGERY,
    UROLOGY,
    GASTROENTEROLOGY,
    ENDOCRINOLOGY,
    PULMONOLOGY
}

